### PR TITLE
let abcnode run from everywhere #53

### LINKED ISSUE #53: abcnode only works if in current folder
If I run abcnode from another folder (e.g. ../abcnode) it fails. I am preparing a PR for this.

I am currently working on a regression test framework. Intitially I process with abcnode. For this I need to start it from another folder than the root of abc2svg.

### PR DESCRIPTION
**Pull request by bwl21**
This fixes #53

### CODE REVIEW

**Comment by moinejf** [comment]
I don't understand your print() added after line 32

**Comment by bwl21** [comment]
Sorry, this was a debug output to help me undestanding what happens

**Comment by moinejf** [comment]
It might be better to have a new clean commit.

**Comment by bwl21** [comment]
I have no clue how to squash commits in a pushed branch. So I did it again and created #55

**Pull request closed without merging**
