### PR TITLE
save abc-text upon change; restore upon start

### PR DESCRIPTION
**Pull request by bwl21**
While testing with edit-1.xhtml, whenever i reload the page (e.g. due to a switch to another commit) i have to reenter the abc code.

I therefore added a feature that edit-1.xhtml restores the latest abc-text upon reload. This also helps, if the user occasionally has left the page in the browser, or restarts after a crash.

Would be glad if you could merge this. Maybe it makes sense to add a preference which toggles this feature.

### CODE REVIEW

**Comment by moinejf** [comment]
You know there are two storage areas: local and session.   
The session storage is destroyed when the browser tab is closed.   
The local storage remains forever, but may be explicitly destroyed.   
The problem is that the browsers load all local storage areas at startup time, on the contrary of the cookies which are loaded when required.

An other problem is that you reload the area each time the source is changed. This implies extra (useless) memory transfers.

Also, you lose the location of the source when this one was loaded by File->Load.

A better solution would be to ask the user to save the source when the page is about to be destroyed.   
In the same way, a button could permit the user to save the source in, either the local storage, or a cookie, or a clipboard, or ...

Personnaly, I save the test examples in the clipboard before reloading the page in Vivaldi. Palemoon does not destroy the source on page reload.

**Comment by bwl21** [comment]
I was using your function assuming thats it uses localstorage. My primary Intention was to simply have the ABC Code back after a refresh. So even session storage would do it.

I did not observe any problem with saving in every change. But we could save on every render operation.

Es i Never Opener a file i was Not aware  of the filename. We could keep this in localstorage  as well.

**Comment by moinejf** [comment]
The local storage values remain forever in the browser data. From my tests with a local http server, I cannot remove these data using the browser settings (delete cookies - the local server is not in the list).

Well, instead of changing the edit.js source, you may use a bookmarklet. This one works fine for me:
```
javascript:var%20v=storage(true,'abc-source');
if(v)elt_ref.source.value=v;
function%20src_change(){
storage(true,'abc-source',elt_ref.source.value);
clearTimeout(timer);if(!playing)timer=setTimeout(render,2000)
};void(0)
```
(you call it after starting my editor)

**Comment by bwl21** [comment]
I did not really get your root concern with the proposed solution.
* you are already storing stuff in localstore
* from usability standpoint it is an improvement without drawbacks
   * User can open the file again (need to do this now as well)
   * User can ctrl-A ctrl- clear the editor pane
   * user can continue the work even after reboot the maching
   * user does not accidentially loose the entered abc

Maybe abc has another quality than a setting. But localstorage is bound to the url, so I don't think it is a problem.

If you consider saving entered abc in localstorage as harmful, we could add an preference option to control the saving. When disabling, you can simply clear the entry in localstorage (`localStorage.removeItem('abc-source')`). You could even add an option "clear localstorage" which removes all entries (`localStorage.clear()`)

I tried the bookmarklet but I think it is not sufficient. After reloading the page I have to click it again to get the abc code back and activate the saving. So the bookmarklet helps me when I refresh the page without saving the abc to the clipboard. 

To be honest, I personally do not like bookmarklets anyhow, they pollute my bookmarkbar, are visible on every page, the code is not provided by the server ...

**Comment by moinejf** [comment]
- I control what I put in the local storage: if the options are standard, nothing is stored, and, anyway, the data are very small (a ABC tune may be 1MB or more - think it must be loaded each time when the browser starts, even it the user will never use the ABC editor).
- the users usually edit their own tunes. They load them (File->Load button), edit them, and then save them. They do not refresh the editor page. They do not close the page before saving. As there is no 'Undo', they think to save their work from time to time. Also, now, the browsers are safe enough and don't crash. Eventually, if they don't like this editor, there are a lot of other ABC editors.

Now, I would say, if you absolutely want this feature, you have all the sources, write your own editor! (in fact, you just have to add a <script> line in edit-1.xhtml and add any code you want).

About the bookmarklets, that's the only hack which remains in the web browsers. I hope they will not drop it as they did with the plugins...

**Comment by bwl21** [comment]
> They do not refresh the page

I do a lot of systematic and random testing with abc2svg. To avoid influences from my app, I use edit-1.xhtml to reproduce the issues. In this testing activities I am going up and down in commit history, trying fixes etc. Thereby I have to reload the page all the time.

And I want to contribute these testing activities based on code provide by you in your github repository, not based on any deviations. I try to provide cases which you can easily reproduce. Therefore forking to  my own editor would not really help.  Of course I use Zupfnoter when I edit abc files for production.

> Also, now, the browsers are safe enough and don't crash. 

BTW: when using edit-1.xthml in vivaldi or firefox, having the focus not in the textpane (e.g. after playing), hitting "Backspace" goes back to the previous page and the work is lost. This happens in Zupfnoter as well, but due to the localstorage, the work is not lost. It was one of the most popular fails in my app which was the reason that I implemented the save to localstorage.

Nevertheless, It is your decision and I accept it.

**Comment by bwl21** [comment]
I have merged the latest master and resolved the conflict. According to your concerns there is now an opt in to to keep ABC source in local storage. So for the casual user there is no difference. But for testing respectively occasional closing of the browser tab it would still be helpful. Therefore, I would appreciate if this could be in the master branch.

Otherwise, please close the PR as wontfix.

**Pull request closed without merging**
